### ISSUE TITLE
Trying example from readme with portal error

### ISSUE THREAD

**Issue by benjamin-asdf** [mentat-collective/emmy-viewers#82]
Hi, this looks awesome I'm trying to set it up. 

```clojure

;; deps.edn:
{:deps
 {djblue/portal {:mvn/version "0.58.2"}
  org.mentat/emmy {:mvn/version "0.32.0"}
  org.mentat/emmy-viewers {:mvn/version "0.3.2"}}
 :paths ["src" "resources"]}


;; user.clj:

(ns user
  (:refer-clojure :exclude
                  [+ - * / zero? compare divide numerator
                   denominator infinite? abs ref partial =])
  (:require [emmy.portal :as ep]
            [portal.api :as p]
            [emmy.env :as e :refer :all]
            [emmy.mafs]
            [emmy.leva]
            [emmy.mathbox]
            [emmy.mathbox.plot]

            [emmy.viewer :as ev]))

;; This really only needs to be run once, but run it at each system start to
;; be safe.
(comment (ep/prepare!))

(def portal
  (ep/start!
   {:emmy.portal/tex {:macros {"\\f" "#1f(#2)"}}
    :theme :portal.colors/zenburn}))

;; this works
(tap> (emmy.mafs/of-x sin {:color :indigo}))

;; this makes a portal render error

;; Rendering error: Could not resolve symbol: emmy.mathbox.components.plot/Scene
;; Error: Could not resolve symbol: emmy.mathbox.components.plot/Scene
;;     at new ul (http://localhost:38689/main.js:3982:75)
;;     at vl.C (http://localhost:38689/main.js:3984:71)
;;     at http://localhost:38689/main.js:5658:173
;;     at r7 (http://localhost:38689/main.js:5658:182)
;;     at http://localhost:38689/main.js:5953:14
;;     at Z (http://localhost:38689/main.js:5614:124)
;;     at http://localhost:38689/main.js:5953:72
;;     at Z (http://localhost:38689/main.js:5614:124)
;;     at http://localhost:38689/main.js:5902:370
;;     at Z (http://localhost:38689/main.js:5614:124)

(tap>
 (emmy.viewer/with-let
     [!phase {:phase 0}]
     (emmy.mathbox.plot/scene
      (emmy.leva/controls
       {:atom !phase
        :folder {:name "Intro Demo"}
        :schema {:phase {:max 4 :min -4 :step 0.01}}})
      (emmy.mathbox.plot/of-y
       {:color "LimeGreen"
        :z (ev/with-params
             {:atom !phase :params [:phase]}
             (fn [shift]
               (fn [y] (* shift (sin (- y shift))))))})
      (emmy.mathbox.plot/of-xy
       {:color "#3090FF"
        :z (ev/with-params {:atom !phase :params [:phase]}
             (fn [shift]
               (fn [[x y]]
                 (+ (((cube D) tanh) x)
                    (sin (- y
                            shift))))))}))))


```

i'm trying to setup the examples with portal, got stuck here.

**Comment by benjamin-asdf** [comment]
as a minor improvement suggestion: 
In the readme the namespace aliases are not consistent between snippets, that made it harder to copy paste them. 

And in the same vein, the first snipped didn't include the requirs / ns form but it would have helped. 

Emmy seems to be a super cool project. Thanks for this already.

**Comment by sritchie** [comment]
Any PRs you want to send to improve this would be welcome!

**Comment by sritchie** [comment]
I see you have

```
;; This really only needs to be run once, but run it at each system start to
;; be safe.
(comment (ep/prepare!))
```
commented out. Can you uncomment that and try again?
